FROM alpine:latest

RUN mkdir -p /usr/portal

WORKDIR /usr/portal
COPY ./src /usr/portal
COPY ./requirements.txt /usr/portal/requirements.txt
COPY ./ssl/ca-cert.pem /usr/local/share/ca-certificates/my-cert.crt

RUN --mount=type=secret,id=CONTAINERIMGVERSION  \
    export CONTAINERIMGVERSION=$(cat /run/secrets/CONTAINERIMGVERSION) && \
    cat /usr/local/share/ca-certificates/my-cert.crt >> /etc/ssl/certs/ca-certificates.crt && \
    apk --no-cache add coreutils python3 py3-pip curl busybox-extras jq ansible && \
    apk --no-cache add --virtual build-dependencies build-base python3-dev && \
    sed -i "s/LOCALTESTING/$CONTAINERIMGVERSION/" /usr/portal/templates/tag.html && \
    pip3 install --upgrade pip && \
    pip3 install -r requirements.txt && \
    ls -l /var/run/secrets && \
    apk add git && \
    apk del build-dependencies && \
    python3 dbops.py && \
    ls -la && \
    python3 jsoncheck.py json/ && \
    python3 jsoncheck.py external_links/ && \
    python3 createroutesfromjson.py > autogeneratedroutes.py  && \
    # initialize db in container
    ls -la /usr/portal


WORKDIR /usr/portal/

EXPOSE 8000

#CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "wsgi:app"]


