from flask import Flask,request,render_template,jsonify,redirect, url_for
import json
from runapi import *

app = Flask(__name__)
# kong puts authenticated groups into this header, retrieve later
#x-authenticated-groups

import staticroutes
import autogeneratedroutes 


if __name__ == '__main__':
    app.run(debug=True, use_reloader=True)
